name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: rust:latest  # Docker image with Rust
        options: --privileged

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Upgrade Rust
      run: |
        rustup upgrade

    - name: Install Python dependencies
      run: |
        python -m venv .venv
        .venv/bin/python -m pip install --upgrade pip uv
        .venv/bin/python -m uv pip install -r requirements.txt

    - name: Build and develop with maturin
      run: .venv/bin/maturin develop

    - name: Run tests
      run: .venv/bin/pytest
